<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\ExpeditionCard;

class ExpeditionCardSeeder extends Seeder{
public function run(): void{
$cards = [
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Kamu mendapat tugas proyek baru yang menarik, tapi deadline-nya sangat ketat. Kamu antusias tapi khawatir bisa deliver tepat waktu.',
'opsi_a_teks'=>'Minta klarifikasi scope dulu sebelum mulai, meski terasa membuang waktu di awal.','opsi_a_mp'=>2,'opsi_a_sp'=>0,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Langsung eksekusi dan beradaptasi seiring jalan, percaya pada kemampuanmu.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Seorang rekan senior memberikan feedback yang cukup tajam tentang presentasimu. Evaluasinya tidak sepenuhnya adil, tapi ada poin yang benar.',
'opsi_a_teks'=>'Terima semua feedback dan berkomitmen memperbaiki tanpa mempertanyakan validitasnya.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Diskusikan balik poin-poin yang kamu anggap tidak adil sambil mengakui yang benar.','opsi_b_mp'=>1,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Kamu diundang ke networking event setelah jam kerja. Kamu lelah dan punya deadline besok, tapi event ini dihadiri orang yang bisa bantu karirmu.',
'opsi_a_teks'=>'Pergi ke event, prioritaskan relasi jangka panjang meski besok lebih berat.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tidak pergi, istirahat dan fokus deliver deadline dengan kualitas terbaik.','opsi_b_mp'=>2,'opsi_b_sp'=>0,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Kamu menyadari bahwa selama ini sering menghindari tugas yang kelihatannya terlalu sulit. Ada satu tugas besar dengan deadline 2 minggu.',
'opsi_a_teks'=>'Pecah tugas menjadi milestone kecil dan mulai dari bagian yang paling kamu kuasai.','opsi_a_mp'=>2,'opsi_a_sp'=>1,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Cari mentor yang lebih berpengalaman untuk membimbingmu mengerjakan.','opsi_b_mp'=>1,'opsi_b_sp'=>1,'opsi_b_tt'=>1,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Atasanmu memuji hasil kerjamu di depan tim, tapi ada bagian yang dibantu rekanmu yang tidak disebutkan.',
'opsi_a_teks'=>'Terima pujian dan nanti privat sampaikan kontribusi rekanmu kepada atasan.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Langsung saat itu sebutkan bahwa ini kerja tim, bukan hanya kamu.','opsi_b_mp'=>1,'opsi_b_sp'=>0,'opsi_b_tt'=>1,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Kamu merasa stuck di comfort zone. Setiap hari terasa rutin tanpa tantangan baru dalam 3 bulan terakhir.',
'opsi_a_teks'=>'Ambil inisiatif mengusulkan proyek improvement ke atasan meski belum diminta.','opsi_a_mp'=>2,'opsi_a_sp'=>1,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Gunakan waktu luang untuk belajar skill baru yang bisa langsung diaplikasikan.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Kamu menemukan kesalahan besar dalam laporan yang sudah dikirim ke klien oleh rekanmu. Rekanmu itu teman dekatmu.',
'opsi_a_teks'=>'Bicara privat dengan rekanmu dan minta dia yang melapor ke atasan.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Langsung lapor ke atasan dengan bukti karena menyangkut integritas perusahaan.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'absence_of_trust'],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Atasan memintamu melakukan sesuatu yang bertentangan dengan nilai-nilaimu. Bukan ilegal, tapi terasa tidak etis.',
'opsi_a_teks'=>'Ikuti arahan atasan karena dia tahu lebih banyak tentang konteks bisnis.','opsi_a_mp'=>-1,'opsi_a_sp'=>0,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Sampaikan keberatan dengan sopan dan tawarkan alternatif yang tetap memenuhi tujuan.','opsi_b_mp'=>2,'opsi_b_sp'=>0,'opsi_b_tt'=>1,'opsi_b_extra'=>null,
'dysfunction_tag'=>'lack_of_commitment'],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Proyekmu dibatalkan tiba-tiba oleh manajemen tanpa penjelasan memadai. Kamu frustrasi dan kehilangan motivasi.',
'opsi_a_teks'=>'Terima keputusan, cari pelajaran dari proses yang sudah dilalui, fokus ke tugas berikutnya.','opsi_a_mp'=>2,'opsi_a_sp'=>0,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Minta meeting dengan manajemen untuk memahami alasan pembatalan.','opsi_b_mp'=>1,'opsi_b_sp'=>1,'opsi_b_tt'=>-1,'opsi_b_extra'=>null,
'dysfunction_tag'=>'inattention_to_results'],
['level'=>'basecamp','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Kamu sering menyalahkan kondisi eksternal atas hasil kerjamu yang tidak optimal. Tim sedang evaluasi kinerja individu.',
'opsi_a_teks'=>'Akui tanggung jawab penuh dan tunjukkan rencana perbaikan konkret.','opsi_a_mp'=>2,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Jelaskan konteks kesulitan yang kamu hadapi secara objektif tanpa menyalahkan siapapun.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>'avoidance_of_accountability'],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Kamu diminta presentasi progress proyek ke stakeholders. Waktu 10 menit, materi banyak.',
'opsi_a_teks'=>'Fokus pada 3 poin kunci dengan data yang kuat, sisanya jadi lampiran.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Buat visualisasi infografis yang ringkas dan biarkan audiens bertanya untuk detail.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>1,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Kamu perlu menguasai tools baru. Ada 2 opsi: training resmi 3 hari atau belajar mandiri seminggu dari resource online.',
'opsi_a_teks'=>'Ikut training resmi — lebih terstruktur dan ada sertifikat.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Belajar mandiri — lebih fleksibel dan langsung praktik di proyek nyata.','opsi_b_mp'=>1,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Email penting yang kamu kirim tidak dibaca penerima. Kamu perlu follow up tapi tidak ingin terkesan mendesak.',
'opsi_a_teks'=>'Kirim ulang email dengan subject baru yang lebih menarik dan tambahkan ringkasan poin.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Telepon atau ajak meeting singkat untuk bahas isi email secara langsung.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>1,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Kamu ditugaskan menulis dokumentasi teknis untuk sistem yang ada. Dokumentasi sebelumnya berantakan dan tidak konsisten.',
'opsi_a_teks'=>'Tulis ulang dari awal dengan template baru yang rapi dan konsisten.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Perbaiki bagian paling kritis dulu dan buat guideline untuk ke depannya.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>1,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Kamu harus selesaikan 3 tugas dengan deadline Jumat. Hari Rabu dan estimasi cuma bisa selesaikan 2 dengan kualitas baik.',
'opsi_a_teks'=>'Negosiasi deadline salah satu tugas, selesaikan 2 lainnya dengan kualitas tinggi.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Kerja lembur untuk menyelesaikan ketiganya, kualitas bisa tidak merata.','opsi_b_mp'=>-1,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Ada peluang sertifikasi profesional relevan, tapi butuh 2 bulan persiapan dan biaya tidak kecil.',
'opsi_a_teks'=>'Ambil sertifikasi dan alokasi waktu khusus untuk persiapan.','opsi_a_mp'=>0,'opsi_a_sp'=>3,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tunda dan fokus pengembangan skill melalui proyek kerja saat ini.','opsi_b_mp'=>1,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Sistem yang kamu kelola downtime di jam sibuk. Kamu tidak tahu penyebabnya dan klien sudah komplain.',
'opsi_a_teks'=>'Kumpulkan tim, delegasikan investigasi, koordinasikan komunikasi ke klien.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Ambil alih investigasi sendiri sambil minta tim lain tangani komunikasi.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'absence_of_trust'],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Cara kamu estimasi waktu proyek selalu meleset. Ada 2 proyek dengan deadline dekat dan estimasi tidak realistis.',
'opsi_a_teks'=>'Akui kesalahan estimasi, usulkan revisi timeline realistis ke stakeholder.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Kerja lembur ekstra dan coba penuhi deadline asli tanpa memberitahu siapapun.','opsi_b_mp'=>-1,'opsi_b_sp'=>2,'opsi_b_tt'=>-1,'opsi_b_extra'=>null,
'dysfunction_tag'=>'avoidance_of_accountability'],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Dua rekan kerja konflik tentang pendekatan teknis berbeda. Masing-masing minta kamu mendukung mereka di meeting besok.',
'opsi_a_teks'=>'Jadikan fasilitator dan bantu mereka temukan titik temu dari kedua pendekatan.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Pilih yang kamu anggap paling tepat dan dukung di meeting.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'fear_of_conflict'],
['level'=>'basecamp','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Kamu diminta ambil alih proyek yang sudah jalan 2 minggu dari orang yang baru resign. Dokumentasi hampir tidak ada.',
'opsi_a_teks'=>'Minta waktu 2 hari untuk audit kondisi sebelum komit timeline baru.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Langsung mulai kerja dan berikan timeline optimis untuk tenangkan klien.','opsi_b_mp'=>-1,'opsi_b_sp'=>2,'opsi_b_tt'=>-1,'opsi_b_extra'=>null,
'dysfunction_tag'=>'lack_of_commitment'],
['level'=>'camp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Anggota tim yang biasanya bagus tiba-tiba menurun. Kamu tahu dia ada masalah pribadi, tapi deadline tidak bisa ditunda.',
'opsi_a_teks'=>'Ajak bicara personal, tawarkan fleksibilitas sementara, redistribusi beban kerja.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tetap tuntut standar kinerja yang sama karena tim lain juga bekerja keras.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Kamu baru dipromosikan jadi lead tim. Bekas rekan selevelmu sekarang bawahanmu. Ada ketegangan halus.',
'opsi_a_teks'=>'Pertahankan gaya komunikasi yang sama seperti sebelum promosi.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tetapkan ekspektasi baru jelas tentang peran dan tanggung jawab masing-masing.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Dalam retrospective, beberapa anggota memberikan feedback negatif tentang cara kamu memimpin meeting.',
'opsi_a_teks'=>'Terima semua feedback terbuka, catat poinnya, komitkan perbaikan di sesi berikutnya.','opsi_a_mp'=>2,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Jelaskan konteks di balik keputusanmu supaya mereka paham alasanmu.','opsi_b_mp'=>1,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Kamu harus memutuskan siapa presentasi ke direksi — ada 2 kandidat sama-sama kompeten dengan gaya berbeda.',
'opsi_a_teks'=>'Pilih yang paling siap dan berikan yang lain kesempatan di forum berbeda.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Buat format co-presentation agar keduanya mendapat exposure yang adil.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>1,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Anggota tim sangat berbakat tapi sulit menerima masukan dan cenderung bekerja sendiri, mengganggu koordinasi.',
'opsi_a_teks'=>'Cari proyek yang butuh keahlian spesifiknya tapi mengharuskan kolaborasi.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Berikan feedback langsung tentang pentingnya kolaborasi dan dampingi prosesnya.','opsi_b_mp'=>1,'opsi_b_sp'=>0,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Tim mencapai target kuartalan tapi sebagian besar kontribusi dari 2-3 orang. Anggota lain tidak berkembang.',
'opsi_a_teks'=>'Buat program mentoring internal di mana top performer membimbing yang lain.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Rotasi tugas agar setiap orang mendapat tantangan baru yang berbeda.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Kamu tahu anggota tim akan di-PHK. Dia tidak tahu dan kamu diminta turunkan evaluasinya sebagai justifikasi.',
'opsi_a_teks'=>'Tolak permintaan dan sampaikan ke HR bahwa kamu tidak bisa menjadi bagian dari proses tidak transparan.','opsi_a_mp'=>2,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Ikuti arahan manajemen karena ini keputusan bisnis.','opsi_b_mp'=>-1,'opsi_b_sp'=>0,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'absence_of_trust'],
['level'=>'camp','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Dua anggota tim berseteru terbuka di meeting. Tim lain diam dan tidak nyaman.',
'opsi_a_teks'=>'Hentikan debat, akui kedua poin pandang, jadwalkan diskusi terpisah untuk selesaikan akar masalah.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Biarkan mereka menyelesaikan sendiri karena konflik kadang diperlukan.','opsi_b_mp'=>0,'opsi_b_sp'=>0,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'fear_of_conflict'],
['level'=>'camp','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Target tim dinaikkan 50% tanpa penambahan resource. Reaksi tim beragam — frustasi, pasrah, marah.',
'opsi_a_teks'=>'Dukung tim dengan menyampaikan keberatan ke manajemen bersama data, minta revisi target.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Motivasi tim dengan framing positif bahwa ini kesempatan membuktikan kapabilitas.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-1,'opsi_b_extra'=>null,
'dysfunction_tag'=>'lack_of_commitment'],
['level'=>'camp','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Anggota tim senior menolak proses barumu. Dia bilang proses lama sudah cukup baik dan perubahan membuang waktu.',
'opsi_a_teks'=>'Dengarkan keberatannya, cari titik valid, libatkan dia dalam penyempurnaan proses baru.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tegaskan keputusan sudah dibuat dan semua wajib mengikutinya.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'avoidance_of_accountability'],
['level'=>'camp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Kamu harus membagikan tugas sprint. Ada tugas penting tapi membosankan, dan tugas menarik tapi impact rendah.',
'opsi_a_teks'=>'Rotasi tugas membosankan secara adil di setiap sprint.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Assign berdasarkan keahlian masing-masing untuk efisiensi terbaik.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Standar code review tidak konsisten — kadang ketat, kadang formalitas. Ini menyebabkan bug yang seharusnya bisa dicegah.',
'opsi_a_teks'=>'Buat checklist wajib untuk code review dan sosialisasikan ke seluruh tim.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Assign reviewer tetap per modul agar paling paham konteksnya.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Meeting tim sering molor dan tidak produktif. Agenda ada tapi sering deviasi ke topik lain.',
'opsi_a_teks'=>'Terapkan timeboxing ketat dan parking lot untuk topik yang melenceng.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>0,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Kurangi frekuensi meeting dan ganti dengan async update via dokumentasi.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>1,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Kamu perlu hiring 1 anggota tim. Budget terbatas dan pasar kerja kompetitif.',
'opsi_a_teks'=>'Fokus pada kandidat dengan growth mindset tinggi meski experience-nya masih minim.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tunggu sampai ketemu kandidat yang benar-benar match semua kriteria.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Klien meminta perubahan spesifikasi signifikan di tengah sprint. Tim sudah commit pada plan awal.',
'opsi_a_teks'=>'Negosiasi masukkan perubahan ke sprint berikutnya, tawarkan solusi interim.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Terima perubahan, rescope sprint, komunikasikan dampaknya transparan ke tim.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Onboarding anggota baru memakan waktu lebih lama. Proses yang ada tidak efektif, anggota baru bingung.',
'opsi_a_teks'=>'Assign buddy untuk setiap anggota baru dan buat 30-day learning plan.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Berikan akses ke semua dokumentasi dan biarkan mereka belajar mandiri.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'camp','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Bug kritis di produksi tepat saat tim merayakan milestone. Bug berasal dari kode yang di-review senior tim.',
'opsi_a_teks'=>'Fokus fix bug dulu, lalu lakukan blameless post-mortem.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Cari tahu siapa yang salah dan pastikan ada konsekuensi agar tidak terulang.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'absence_of_trust'],
['level'=>'camp','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Dua subtim membuat keputusan teknis bertentangan untuk modul yang saling terhubung. Integrasi minggu depan bermasalah.',
'opsi_a_teks'=>'Panggil kedua lead, fasilitasi diskusi teknis untuk temukan arsitektur yang menyatukan keduanya.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Putuskan sendiri arsitektur yang lebih baik dan minta kedua pihak mengikutinya.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'fear_of_conflict'],
['level'=>'camp','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Anggota tim paling berpengalaman mengajukan resign. Dia knowledge base untuk sistem kritis, belum ada dokumentasi memadai.',
'opsi_a_teks'=>'Negosiasi masa transisi 1 bulan dan jalankan knowledge transfer intensif.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Terima resign segera dan distribusikan tugasnya ke anggota lain.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-1,'opsi_b_extra'=>null,
'dysfunction_tag'=>'lack_of_commitment'],
['level'=>'camp','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Beberapa anggota diam-diam memotong proses QA karena merasa lambat. Penyebab peningkatan bug di produksi.',
'opsi_a_teks'=>'Investigasi alasan pemotongan proses, perbaiki proses QA yang memang terlalu berat.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tegaskan QA wajib dan berikan warning ke yang melanggar.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'avoidance_of_accountability'],
['level'=>'summit','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Kamu mengelola 3 team lead dengan gaya kepemimpinan sangat berbeda: satu otoriter, satu demokratis, satu laissez-faire.',
'opsi_a_teks'=>'Buat forum reguler di mana mereka berbagi challenge dan belajar dari perbedaan gaya.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tetapkan standar kepemimpinan minimum yang harus dipatuhi semua, sisanya biarkan berekspresi.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'summit','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'CEO meminta visi 3 tahun untuk divisi kamu. Kamu punya ide kuat tapi tanpa buy-in para lead, eksekusinya gagal.',
'opsi_a_teks'=>'Workshop bersama para lead untuk rumuskan visi bersama, lalu kamu kristalisasi untuk CEO.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Susun visi sendiri berdasarkan analisis mendalam dan presentasikan ke para lead untuk feedback.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'summit','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Salah satu team lead menunjukkan potensi luar biasa dan siap naik level. Tapi jika dipromosikan, timnya kehilangan momentum.',
'opsi_a_teks'=>'Siapkan successor-nya sekarang, promosikan dalam 2-3 bulan dengan transisi terencana.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tunda promosi sampai timnya benar-benar stabil dengan performa konsisten.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'summit','kategori'=>'mindset','tipe'=>'netral',
'teks_situasi'=>'Organisasi mengalami perubahan strategi besar. Para lead bingung tentang prioritas baru, tim kehilangan fokus.',
'opsi_a_teks'=>'Kumpulkan semua lead, breakdown strategi baru menjadi inisiatif per tim, bantu translate ke eksekusi.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Buat dokumen strategi detail dan distribusikan, biarkan lead mengartikulasikan sendiri ke timnya.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'summit','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Dua team lead bersaing untuk posisi kosong. Persaingan merusak kolaborasi dan menimbulkan politik internal.',
'opsi_a_teks'=>'Buat proses seleksi transparan dan objektif, pastikan yang kalah tetap mendapat pengembangan.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Pilih yang paling siap secara diam-diam dan kontrol informasi agar tidak menimbulkan gejolak.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-3,'opsi_b_extra'=>null,
'dysfunction_tag'=>'absence_of_trust'],
['level'=>'summit','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Dalam meeting leadership, ada keputusan kontroversial. Semua lead diam menunggu arahanmu.',
'opsi_a_teks'=>'Paksa diskusi dengan meminta setiap lead menyatakan pendapatnya sebelum kamu memberikan pandangan.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Ambil keputusan sendiri dan komunikasikan reasoning-nya secara jelas setelahnya.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'fear_of_conflict'],
['level'=>'summit','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Board minta pemotongan budget 30%. Kamu harus komunikasikan ke para lead yang sudah commit plan tahunan.',
'opsi_a_teks'=>'Libatkan para lead dalam reprioritization, berikan mereka otoritas tentukan apa yang dipotong.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>3,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tentukan sendiri pemotongan per tim berdasarkan data objektif sebagai keputusan final.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'lack_of_commitment'],
['level'=>'summit','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Team lead sering mengambil credit untuk kerja timnya saat presentasi ke direksi. Timnya resah.',
'opsi_a_teks'=>'Bicarakan privat, tunjukkan data dampaknya, bantu perbaiki kebiasaannya.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Angkat isu ini di forum leadership sebagai contoh budaya yang harus dihindari.','opsi_b_mp'=>0,'opsi_b_sp'=>0,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'avoidance_of_accountability'],
['level'=>'summit','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Tim terbaikmu mencapai semua KPI tapi dengan cara merusak hubungan tim lain (hoarding resource, tidak berbagi info).',
'opsi_a_teks'=>'Apresiasi hasilnya tapi tegaskan caranya tidak sejalan dengan budaya organisasi.','opsi_a_mp'=>1,'opsi_a_sp'=>0,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Biarkan karena hasilnya penting untuk organisasi, urusan internal bisa disesuaikan nanti.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-3,'opsi_b_extra'=>null,
'dysfunction_tag'=>'inattention_to_results'],
['level'=>'summit','kategori'=>'mindset','tipe'=>'krisis',
'teks_situasi'=>'Kamu ditawari memimpin divisi baru lebih besar, tapi meninggalkan tim yang kamu bangun 2 tahun di saat mereka paling butuh arahan.',
'opsi_a_teks'=>'Terima tawaran tapi pastikan succession plan kuat dan tetap support tim lama sebagai mentor.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tolak tawaran karena komitmenmu kepada tim saat ini adalah prioritas.','opsi_b_mp'=>2,'opsi_b_sp'=>0,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>'lack_of_commitment'],
['level'=>'summit','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Kamu perlu mengukur efektivitas 5 tim secara adil dengan KPI dan konteks berbeda-beda.',
'opsi_a_teks'=>'Buat framework evaluasi yang mengukur leading indicators dan lagging indicators dengan bobot disepakati.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Gunakan OKR standar untuk semua tim dengan customization minimal per konteks.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'summit','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Budget pelatihan terbatas. 5 team lead mengajukan program berbeda. Total permintaan 3x lipat budget.',
'opsi_a_teks'=>'Buat pooled learning budget dan minta lead memprioritasi bersama yang paling impact untuk divisi.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Alokasi proporsional berdasarkan ukuran tim dan kebutuhan yang terbukti data.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'summit','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Organisasi mau adopsi framework baru. Para lead punya skeptisisme berbeda.',
'opsi_a_teks'=>'Jalankan pilot di 1-2 tim yang paling terbuka, buktikan hasilnya, lalu scale gradual.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Rollout sekaligus ke semua tim dengan training intensif dan monitoring ketat.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'summit','kategori'=>'skillset','tipe'=>'netral',
'teks_situasi'=>'Kamu perlu presentasi kinerja divisi ke board. Data menunjukkan hasil campuran — peningkatan signifikan di beberapa area, penurunan di area lain.',
'opsi_a_teks'=>'Presentasi transparan dengan focus pada pembelajaran dan rencana aksi untuk area yang menurun.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Highlight area yang berhasil dan minimalkan area yang menurun dengan framing konteks yang memihak.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>-1,'opsi_b_extra'=>null,
'dysfunction_tag'=>null],
['level'=>'summit','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Investigasi internal mengungkap satu tim melaporkan metrik yang dipoles selama 6 bulan. Lead klaim hanya mengikuti budaya yang sudah ada.',
'opsi_a_teks'=>'Tangani sistemik: audit metrik semua tim, perbaiki proses pelaporan, latih ulang para lead.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Berikan sanksi tegas ke lead sebagai contoh untuk semua.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>-3,'opsi_b_extra'=>null,
'dysfunction_tag'=>'absence_of_trust'],
['level'=>'summit','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Dua tim debat terbuka di slack tentang arsitektur. Debat sudah menyerang personal, produktivitas kedua tim turun 40%.',
'opsi_a_teks'=>'Mediasi langsung, bawa kedua lead ke ruangan, fasilitasi diskusi berbasis data.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Putuskan sendiri arsitektur yang benar dan larang perdebatan lebih lanjut.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>-3,'opsi_b_extra'=>null,
'dysfunction_tag'=>'fear_of_conflict'],
['level'=>'summit','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'CEO umumkan pivot besar di all-hands. Para lead tidak di-brief sebelumnya dan kaget.',
'opsi_a_teks'=>'Segera kumpulkan para lead, breakdown implikasi pivot, buat rencana transisi 30 hari.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Sampaikan ke tim bahwa kamu juga baru tahu dan minta mereka bersabar.','opsi_b_mp'=>0,'opsi_b_sp'=>0,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'lack_of_commitment'],
['level'=>'summit','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Team lead membiarkan anggota underperform tanpa intervensi karena tidak mau terlihat kejam.',
'opsi_a_teks'=>'Coaching intensif tentang performance management yang tulus tapi tegas, dampingi prosesnya.','opsi_a_mp'=>0,'opsi_a_sp'=>1,'opsi_a_tt'=>2,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Ambil alih proses performance management langsung untuk anggota yang underperform.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>-2,'opsi_b_extra'=>null,
'dysfunction_tag'=>'avoidance_of_accountability'],
['level'=>'summit','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'3 dari 5 tim menghabiskan 30% waktu untuk internal politics — meeting tidak produktif, reporting berlebihan, silo communication.',
'opsi_a_teks'=>'Implementasi bureaucracy audit: identifikasi dan eliminasi aktivitas yang tidak memberikan value ke customer.','opsi_a_mp'=>0,'opsi_a_sp'=>2,'opsi_a_tt'=>1,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tetapkan KPI baru yang mengukur output nyata, kurangi KPI berbasis aktivitas internal.','opsi_b_mp'=>0,'opsi_b_sp'=>1,'opsi_b_tt'=>0,'opsi_b_extra'=>null,
'dysfunction_tag'=>'inattention_to_results'],
['level'=>'summit','kategori'=>'skillset','tipe'=>'krisis',
'teks_situasi'=>'Perusahaan merger. Kamu harus integrasikan 2 tim leadership dengan budaya sangat berbeda. Tim lama merasa terancam, tim baru merasa tidak dihargai.',
'opsi_a_teks'=>'Workshop merged culture di mana kedua pihak berkontribusi menetapkan nilai-nilai dan cara kerja baru.','opsi_a_mp'=>1,'opsi_a_sp'=>1,'opsi_a_tt'=>3,'opsi_a_extra'=>null,
'opsi_b_teks'=>'Tetapkan culture perusahaan yang sudah ada sebagai standar, minta tim baru beradaptasi.','opsi_b_mp'=>0,'opsi_b_sp'=>2,'opsi_b_tt'=>-3,'opsi_b_extra'=>null,
'dysfunction_tag'=>'absence_of_trust'],
];
foreach($cards as $card) ExpeditionCard::create($card);
$this->command->info(count($cards).' expedition cards seeded.');
}
}

