@extends('layouts.app')
<div class="max-w-2xl mx-auto px-4 pt-6 pb-8">
<h1 class="text-2xl font-bold font-expedition text-mountain-100 mb-6">{{ $card?'Edit #'.$card->id:'Tambah Kartu' }}</h1>
<form method="POST" action="{{ $card?route('admin.cards.update',$card):route('admin.cards.store') }}" class="space-y-4">@csrf @if($card)@method('PUT')@endif
<div class="grid grid-cols-3 gap-3">
<div><label class="block text-xs text-mountain-400 mb-1">Level</label><select name="level" class="w-full px-3 py-2 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm"><option value="basecamp" {{ ($card->level??'')==='basecamp'?'selected':'' }}>Basecamp</option><option value="camp" {{ ($card->level??'')==='camp'?'selected':'' }}>Camp</option><option value="summit" {{ ($card->level??'')==='summit'?'selected':'' }}>Summit</option></select></div>
<div><label class="block text-xs text-mountain-400 mb-1">Kategori</label><select name="kategori" class="w-full px-3 py-2 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm"><option value="mindset" {{ ($card->kategori??'')==='mindset'?'selected':'' }}>Mindset</option><option value="skillset" {{ ($card->kategori??'')==='skillset'?'selected':'' }}>Skillset</option></select></div>
<div><label class="block text-xs text-mountain-400 mb-1">Tipe</label><select name="tipe" class="w-full px-3 py-2 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm"><option value="netral" {{ ($card->tipe??'')==='netral'?'selected':'' }}>Netral</option><option value="krisis" {{ ($card->tipe??'')==='krisis'?'selected':'' }}>Krisis</option></select></div></div>
<div><label class="block text-xs text-mountain-400 mb-1">Situasi</label><textarea name="teks_situasi" rows="3" class="w-full px-3 py-2 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm">{{ $card->teks_situasi??'' }}</textarea></div>
<div class="grid grid-cols-2 gap-4">
<div class="p-4 rounded-xl bg-mountain-900/50 border border-mountain-800"><h3 class="text-sm font-bold text-mountain-200 mb-3">Opsi A</h3>
<textarea name="opsi_a_teks" rows="2" class="w-full px-3 py-2 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm mb-2" placeholder="Teks A">{{ $card->opsi_a_teks??'' }}</textarea>
<div class="grid grid-cols-3 gap-2"><div><label class="text-xs text-mountain-400">MP</label><input type="number" name="opsi_a_mp" value="{{ $card->opsi_a_mp??0 }}" class="w-full px-2 py-1.5 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm text-center"></div>
<div><label class="text-xs text-mountain-400">SP</label><input type="number" name="opsi_a_sp" value="{{ $card->opsi_a_sp??0 }}" class="w-full px-2 py-1.5 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm text-center"></div>
<div><label class="text-xs text-mountain-400">TT</label><input type="number" name="opsi_a_tt" value="{{ $card->opsi_a_tt??0 }}" class="w-full px-2 py-1.5 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm text-center"></div></div></div>
<div class="p-4 rounded-xl bg-mountain-900/50 border border-mountain-800"><h3 class="text-sm font-bold text-mountain-200 mb-3">Opsi B</h3>
<textarea name="opsi_b_teks" rows="2" class="w-full px-3 py-2 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm mb-2" placeholder="Teks B">{{ $card->opsi_b_teks??'' }}</textarea>
<div class="grid grid-cols-3 gap-2"><div><label class="text-xs text-mountain-400">MP</label><input type="number" name="opsi_b_mp" value="{{ $card->opsi_b_mp??0 }}" class="w-full px-2 py-1.5 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm text-center"></div>
<div><label class="text-xs text-mountain-400">SP</label><input type="number" name="opsi_b_sp" value="{{ $card->opsi_b_sp??0 }}" class="w-full px-2 py-1.5 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm text-center"></div>
<div><label class="text-xs text-mountain-400">TT</label><input type="number" name="opsi_b_tt" value="{{ $card->opsi_b_tt??0 }}" class="w-full px-2 py-1.5 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm text-center"></div></div></div></div>
<div><label class="block text-xs text-mountain-400 mb-1">Dysfunction</label><select name="dysfunction_tag" class="w-full px-3 py-2 rounded-lg bg-mountain-800 border border-mountain-700 text-mountain-100 text-sm">
<option value="">— Tidak ada —</option>@foreach(config('summit.dysfunctions') as $k=>$v)<option value="{{ $k }}" {{ ($card->dysfunction_tag??'')===$k?'selected':'' }}>{{ $v }}</option>@endforeach</select></div>
<div class="flex gap-3 pt-2"><a href="{{ route('admin.cards.index') }}" class="px-4 py-2 rounded-xl border border-mountain-600 text-mountain-300 text-sm">Batal</a>
<button class="px-6 py-2 rounded-xl bg-trust-500 text-mountain-950 font-bold text-sm">Simpan</button></div></form></div>
